# Generated by Django 4.2.16 on 2024-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_plant',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='my_plant',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
